// @ts-nocheck
import { Context } from "https://edge.netlify.com";

const SYSTEM_PROMPT = `
You are the Vulpine AI Estimator, an automated sales engineer for an elite agency. You provide high-level cost and time estimates for software engineering, AI integration, and Shopify engineering.

CRITICAL INSTRUCTIONS & BOUNDARIES:
1. THE VULPINE STACK: Vulpine exclusively engineers on the following stack:
   - Web/Software: JavaScript, TypeScript, Node.js, and Stencil (Web Components).
   - Platform: Shopify ONLY. We handle Liquid themes, Shopify Extensibility (sandboxed React), Headless (via Stencil), and Storefront/Admin APIs.
   - AI/Agentic: Python, UV, LangChain, HuggingFace, custom LLM integrations (specializing in Gemini 3+).
   - Services: "Anti-gravity agentic-first engineering" (accelerating dev using AI), custom AI products, agentic orchestration, coaching, and SDK bridging. We are open to ANY AI/LLM engineering.
2. THE PIVOT (UPSELL): If a user requests work on legacy or non-target platforms (e.g., Magento, WordPress, WooCommerce, PHP), DO NOT provide an estimate for that platform. Instead, explain that Vulpine exclusively engineers high-performance Shopify and AI solutions, and offer an estimate to MIGRATE them off their legacy stack onto Shopify or modern Headless architecture.
3. OFF-TOPIC RULE: If the query is completely unrelated to tech/engineering/commerce/AI (e.g. recipes, writing code, general knowledge), reply exactly with: "I am specifically tuned to calculate project scopes for Vulpine's core services. I cannot assist with unrelated queries."
4. TONE: Maintain a confident, cutting-edge, yet approachable tone. Act as a senior technical architect.
5. FORMATTING: Use markdown headings (###) and bullet points. Be concise.

ESTIMATION LOGIC & PRICING:
- Day Rate: £250 GBP per day.
- Speed: We utilize Agentic Development, making us significantly faster than conventional agencies.
- Timeframes (Examples):
  - Typical Shopify builds: 20 to 120+ hours (2.5 to 15+ days) depending on complexity.
  - Conventional web dev (custom sites/apps): 20 to 40+ hours (2.5 to 5+ days).
- Calculation: Estimate the base hours needed, convert to days, multiply by £250. THEN, add exactly 20% to the final cost to account for communications, meetings, and design time.
- Currency: ALWAYS output costs in GBP (£).

STRUCTURE YOUR RESPONSE:
1. Technical Approach: Briefly summarize how Vulpine will solve their problem using our specific stack. (Pivot to Shopify if they asked for Magento/WP).
2. Estimated Time: Provide a realistic range in hours/days.
3. Estimated Cost: Provide the final cost range in GBP (£), explicitly mentioning that a 20% buffer for comms/design is included.
4. Caveat: You MUST conclude by stating that this is a rough estimate generated by an AI, and final quotes are subject to change based on full scope discovery (e.g., product range, existing designs, integrations).
`;

// Simple in-memory rate limiting map for the edge isolate.
// Note: Edge isolates spin up and down, so this isn't global, but it stops rapid-fire spam on a single node.
const rateLimitMap = new Map<string, { count: number; timestamp: number }>();
const RATE_LIMIT_WINDOW_MS = 60000; // 1 minute
const MAX_REQUESTS_PER_WINDOW = 5;

export default async (request: Request, context: Context) => {
  if (request.method !== "POST") {
    return new Response("Method Not Allowed", { status: 405 });
  }

  try {
    const { projectDescription, token } = await request.json();

    if (!projectDescription) {
      return new Response(JSON.stringify({ error: "Project description is required." }), {
        status: 400,
        headers: { "Content-Type": "application/json" }
      });
    }

    if (!token) {
      return new Response(JSON.stringify({ error: "Security token is missing. Please refresh." }), {
        status: 400,
        headers: { "Content-Type": "application/json" }
      });
    }

    const recaptchaSecret = Deno.env.get("RECAPTCHA_SECRET_KEY");
    if (!recaptchaSecret) {
      console.error("RECAPTCHA_SECRET_KEY is not set.");
      return new Response(JSON.stringify({ error: "Server misconfiguration." }), {
        status: 500,
        headers: { "Content-Type": "application/json" }
      });
    }

    // Verify reCAPTCHA token
    const verifyParams = new URLSearchParams();
    verifyParams.append('secret', recaptchaSecret);
    verifyParams.append('response', token);
    
    const verifyResponse = await fetch('https://www.google.com/recaptcha/api/siteverify', {
      method: 'POST',
      body: verifyParams
    });
    
    const verifyData = await verifyResponse.json();
    
    // We enforce a strict score threshold (0.5) to block bots.
    if (!verifyData.success || verifyData.score < 0.5) {
      console.warn(`ReCaptcha failed. Score: ${verifyData.score}`);
      return new Response(JSON.stringify({ error: "Automated traffic detected. Request blocked." }), {
        status: 403,
        headers: { "Content-Type": "application/json" }
      });
    }

    // --- Rate Limiting Logic ---
    const ip = context.ip || "unknown";
    const now = Date.now();

    if (!rateLimitMap.has(ip)) {
      rateLimitMap.set(ip, { count: 1, timestamp: now });
    } else {
      const data = rateLimitMap.get(ip)!;
      if (now - data.timestamp > RATE_LIMIT_WINDOW_MS) {
        // Reset window
        rateLimitMap.set(ip, { count: 1, timestamp: now });
      } else {
        data.count++;
        if (data.count > MAX_REQUESTS_PER_WINDOW) {
          console.warn(`Rate limit triggered for IP: ${ip}`);
          return new Response(JSON.stringify({ error: "Too many estimates requested. Please try again in a minute." }), {
            status: 429,
            headers: { "Content-Type": "application/json" }
          });
        }
      }
    }
    // ---------------------------

    const apiKey = Deno.env.get("GEMINI_API_KEY");
    if (!apiKey) {
      console.error("GEMINI_API_KEY is not set.");
      return new Response(JSON.stringify({ error: "Configuration error on server." }), {
        status: 500,
        headers: { "Content-Type": "application/json" }
      });
    }

    // Call the Gemini API via standard fetch to keep it lightweight on the Edge
    const geminiEndpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key=${apiKey}`;

    const geminiPayload = {
      system_instruction: {
        parts: [{ text: SYSTEM_PROMPT }]
      },
      contents: [{
        role: "user",
        parts: [{ text: `Project description: ${projectDescription}` }]
      }]
    };

    const response = await fetch(geminiEndpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(geminiPayload)
    });

    if (!response.ok) {
      const errorData = await response.text();
      console.error("Gemini API Error:", errorData);
      return new Response(JSON.stringify({ error: "Failed to generate estimate." }), {
        status: 502,
        headers: { "Content-Type": "application/json" }
      });
    }

    const data = await response.json();

    // Extract text from the Gemini response structure
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text || "No estimate could be generated.";

    return new Response(JSON.stringify({ estimate: generatedText }), {
      status: 200,
      headers: { "Content-Type": "application/json" }
    });

  } catch (error) {
    console.error("Edge function error:", error);
    return new Response(JSON.stringify({ error: "Internal Server Error" }), {
      status: 500,
      headers: { "Content-Type": "application/json" }
    });
  }
};
