/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAbout {
    }
    interface AppBlog {
        "initialSlug": string;
    }
    interface AppCaseStudies {
    }
    interface AppContact {
    }
    interface AppCsCraftAndBerry {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppServices {
        "serviceType": 'ai' | 'shopify';
    }
    interface AppWorkWithUs {
    }
    interface FoxyBusinessCard {
    }
    interface FoxyConstellation {
    }
    interface FoxyCta {
        "url": string;
    }
    interface FoxyDebateTakeover {
        "active": boolean;
    }
    interface FoxyEstimate {
    }
    interface FoxyFooter {
    }
    interface FoxyHero {
        "headline": string;
        "subheadline": string;
    }
    interface FoxyJournalRenderer {
        "slug": string;
    }
    interface FoxyLogo {
        "size": 'small' | 'medium' | 'large';
    }
    interface FoxyModal {
        "aiOutput": string;
        "isOpen": boolean;
        "modalTitle": string;
    }
    interface FoxyNav {
        "active": boolean;
        "resetDrilldown": () => Promise<void>;
    }
    interface FoxyToast {
        "message": string;
        "toastId": string;
        "type": 'alert' | 'success' | 'info';
    }
    interface FoxyToastContainer {
    }
}
export interface FoxyDebateTakeoverCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFoxyDebateTakeoverElement;
}
export interface FoxyJournalRendererCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFoxyJournalRendererElement;
}
export interface FoxyModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFoxyModalElement;
}
export interface FoxyNavCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFoxyNavElement;
}
export interface FoxyToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFoxyToastElement;
}
declare global {
    interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {
    }
    var HTMLAppAboutElement: {
        prototype: HTMLAppAboutElement;
        new (): HTMLAppAboutElement;
    };
    interface HTMLAppBlogElement extends Components.AppBlog, HTMLStencilElement {
    }
    var HTMLAppBlogElement: {
        prototype: HTMLAppBlogElement;
        new (): HTMLAppBlogElement;
    };
    interface HTMLAppCaseStudiesElement extends Components.AppCaseStudies, HTMLStencilElement {
    }
    var HTMLAppCaseStudiesElement: {
        prototype: HTMLAppCaseStudiesElement;
        new (): HTMLAppCaseStudiesElement;
    };
    interface HTMLAppContactElement extends Components.AppContact, HTMLStencilElement {
    }
    var HTMLAppContactElement: {
        prototype: HTMLAppContactElement;
        new (): HTMLAppContactElement;
    };
    interface HTMLAppCsCraftAndBerryElement extends Components.AppCsCraftAndBerry, HTMLStencilElement {
    }
    var HTMLAppCsCraftAndBerryElement: {
        prototype: HTMLAppCsCraftAndBerryElement;
        new (): HTMLAppCsCraftAndBerryElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppServicesElement extends Components.AppServices, HTMLStencilElement {
    }
    var HTMLAppServicesElement: {
        prototype: HTMLAppServicesElement;
        new (): HTMLAppServicesElement;
    };
    interface HTMLAppWorkWithUsElement extends Components.AppWorkWithUs, HTMLStencilElement {
    }
    var HTMLAppWorkWithUsElement: {
        prototype: HTMLAppWorkWithUsElement;
        new (): HTMLAppWorkWithUsElement;
    };
    interface HTMLFoxyBusinessCardElement extends Components.FoxyBusinessCard, HTMLStencilElement {
    }
    var HTMLFoxyBusinessCardElement: {
        prototype: HTMLFoxyBusinessCardElement;
        new (): HTMLFoxyBusinessCardElement;
    };
    interface HTMLFoxyConstellationElement extends Components.FoxyConstellation, HTMLStencilElement {
    }
    var HTMLFoxyConstellationElement: {
        prototype: HTMLFoxyConstellationElement;
        new (): HTMLFoxyConstellationElement;
    };
    interface HTMLFoxyCtaElement extends Components.FoxyCta, HTMLStencilElement {
    }
    var HTMLFoxyCtaElement: {
        prototype: HTMLFoxyCtaElement;
        new (): HTMLFoxyCtaElement;
    };
    interface HTMLFoxyDebateTakeoverElementEventMap {
        "debateClose": void;
    }
    interface HTMLFoxyDebateTakeoverElement extends Components.FoxyDebateTakeover, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFoxyDebateTakeoverElementEventMap>(type: K, listener: (this: HTMLFoxyDebateTakeoverElement, ev: FoxyDebateTakeoverCustomEvent<HTMLFoxyDebateTakeoverElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFoxyDebateTakeoverElementEventMap>(type: K, listener: (this: HTMLFoxyDebateTakeoverElement, ev: FoxyDebateTakeoverCustomEvent<HTMLFoxyDebateTakeoverElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFoxyDebateTakeoverElement: {
        prototype: HTMLFoxyDebateTakeoverElement;
        new (): HTMLFoxyDebateTakeoverElement;
    };
    interface HTMLFoxyEstimateElement extends Components.FoxyEstimate, HTMLStencilElement {
    }
    var HTMLFoxyEstimateElement: {
        prototype: HTMLFoxyEstimateElement;
        new (): HTMLFoxyEstimateElement;
    };
    interface HTMLFoxyFooterElement extends Components.FoxyFooter, HTMLStencilElement {
    }
    var HTMLFoxyFooterElement: {
        prototype: HTMLFoxyFooterElement;
        new (): HTMLFoxyFooterElement;
    };
    interface HTMLFoxyHeroElement extends Components.FoxyHero, HTMLStencilElement {
    }
    var HTMLFoxyHeroElement: {
        prototype: HTMLFoxyHeroElement;
        new (): HTMLFoxyHeroElement;
    };
    interface HTMLFoxyJournalRendererElementEventMap {
        "closeModal": void;
    }
    interface HTMLFoxyJournalRendererElement extends Components.FoxyJournalRenderer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFoxyJournalRendererElementEventMap>(type: K, listener: (this: HTMLFoxyJournalRendererElement, ev: FoxyJournalRendererCustomEvent<HTMLFoxyJournalRendererElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFoxyJournalRendererElementEventMap>(type: K, listener: (this: HTMLFoxyJournalRendererElement, ev: FoxyJournalRendererCustomEvent<HTMLFoxyJournalRendererElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFoxyJournalRendererElement: {
        prototype: HTMLFoxyJournalRendererElement;
        new (): HTMLFoxyJournalRendererElement;
    };
    interface HTMLFoxyLogoElement extends Components.FoxyLogo, HTMLStencilElement {
    }
    var HTMLFoxyLogoElement: {
        prototype: HTMLFoxyLogoElement;
        new (): HTMLFoxyLogoElement;
    };
    interface HTMLFoxyModalElementEventMap {
        "modalClose": void;
    }
    interface HTMLFoxyModalElement extends Components.FoxyModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFoxyModalElementEventMap>(type: K, listener: (this: HTMLFoxyModalElement, ev: FoxyModalCustomEvent<HTMLFoxyModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFoxyModalElementEventMap>(type: K, listener: (this: HTMLFoxyModalElement, ev: FoxyModalCustomEvent<HTMLFoxyModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFoxyModalElement: {
        prototype: HTMLFoxyModalElement;
        new (): HTMLFoxyModalElement;
    };
    interface HTMLFoxyNavElementEventMap {
        "menuClose": void;
        "drilldownChange": boolean;
        "openDebate": void;
    }
    interface HTMLFoxyNavElement extends Components.FoxyNav, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFoxyNavElementEventMap>(type: K, listener: (this: HTMLFoxyNavElement, ev: FoxyNavCustomEvent<HTMLFoxyNavElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFoxyNavElementEventMap>(type: K, listener: (this: HTMLFoxyNavElement, ev: FoxyNavCustomEvent<HTMLFoxyNavElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFoxyNavElement: {
        prototype: HTMLFoxyNavElement;
        new (): HTMLFoxyNavElement;
    };
    interface HTMLFoxyToastElementEventMap {
        "foxy-toast-dismissed": string;
    }
    interface HTMLFoxyToastElement extends Components.FoxyToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFoxyToastElementEventMap>(type: K, listener: (this: HTMLFoxyToastElement, ev: FoxyToastCustomEvent<HTMLFoxyToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFoxyToastElementEventMap>(type: K, listener: (this: HTMLFoxyToastElement, ev: FoxyToastCustomEvent<HTMLFoxyToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFoxyToastElement: {
        prototype: HTMLFoxyToastElement;
        new (): HTMLFoxyToastElement;
    };
    interface HTMLFoxyToastContainerElement extends Components.FoxyToastContainer, HTMLStencilElement {
    }
    var HTMLFoxyToastContainerElement: {
        prototype: HTMLFoxyToastContainerElement;
        new (): HTMLFoxyToastContainerElement;
    };
    interface HTMLElementTagNameMap {
        "app-about": HTMLAppAboutElement;
        "app-blog": HTMLAppBlogElement;
        "app-case-studies": HTMLAppCaseStudiesElement;
        "app-contact": HTMLAppContactElement;
        "app-cs-craft-and-berry": HTMLAppCsCraftAndBerryElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "app-services": HTMLAppServicesElement;
        "app-work-with-us": HTMLAppWorkWithUsElement;
        "foxy-business-card": HTMLFoxyBusinessCardElement;
        "foxy-constellation": HTMLFoxyConstellationElement;
        "foxy-cta": HTMLFoxyCtaElement;
        "foxy-debate-takeover": HTMLFoxyDebateTakeoverElement;
        "foxy-estimate": HTMLFoxyEstimateElement;
        "foxy-footer": HTMLFoxyFooterElement;
        "foxy-hero": HTMLFoxyHeroElement;
        "foxy-journal-renderer": HTMLFoxyJournalRendererElement;
        "foxy-logo": HTMLFoxyLogoElement;
        "foxy-modal": HTMLFoxyModalElement;
        "foxy-nav": HTMLFoxyNavElement;
        "foxy-toast": HTMLFoxyToastElement;
        "foxy-toast-container": HTMLFoxyToastContainerElement;
    }
}
declare namespace LocalJSX {
    interface AppAbout {
    }
    interface AppBlog {
        "initialSlug"?: string;
    }
    interface AppCaseStudies {
    }
    interface AppContact {
    }
    interface AppCsCraftAndBerry {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppServices {
        "serviceType"?: 'ai' | 'shopify';
    }
    interface AppWorkWithUs {
    }
    interface FoxyBusinessCard {
    }
    interface FoxyConstellation {
    }
    interface FoxyCta {
        "url"?: string;
    }
    interface FoxyDebateTakeover {
        "active"?: boolean;
        "onDebateClose"?: (event: FoxyDebateTakeoverCustomEvent<void>) => void;
    }
    interface FoxyEstimate {
    }
    interface FoxyFooter {
    }
    interface FoxyHero {
        "headline"?: string;
        "subheadline"?: string;
    }
    interface FoxyJournalRenderer {
        "onCloseModal"?: (event: FoxyJournalRendererCustomEvent<void>) => void;
        "slug"?: string;
    }
    interface FoxyLogo {
        "size"?: 'small' | 'medium' | 'large';
    }
    interface FoxyModal {
        "aiOutput"?: string;
        "isOpen"?: boolean;
        "modalTitle"?: string;
        "onModalClose"?: (event: FoxyModalCustomEvent<void>) => void;
    }
    interface FoxyNav {
        "active"?: boolean;
        "onDrilldownChange"?: (event: FoxyNavCustomEvent<boolean>) => void;
        "onMenuClose"?: (event: FoxyNavCustomEvent<void>) => void;
        "onOpenDebate"?: (event: FoxyNavCustomEvent<void>) => void;
    }
    interface FoxyToast {
        "message"?: string;
        "onFoxy-toast-dismissed"?: (event: FoxyToastCustomEvent<string>) => void;
        "toastId"?: string;
        "type"?: 'alert' | 'success' | 'info';
    }
    interface FoxyToastContainer {
    }
    interface IntrinsicElements {
        "app-about": AppAbout;
        "app-blog": AppBlog;
        "app-case-studies": AppCaseStudies;
        "app-contact": AppContact;
        "app-cs-craft-and-berry": AppCsCraftAndBerry;
        "app-home": AppHome;
        "app-root": AppRoot;
        "app-services": AppServices;
        "app-work-with-us": AppWorkWithUs;
        "foxy-business-card": FoxyBusinessCard;
        "foxy-constellation": FoxyConstellation;
        "foxy-cta": FoxyCta;
        "foxy-debate-takeover": FoxyDebateTakeover;
        "foxy-estimate": FoxyEstimate;
        "foxy-footer": FoxyFooter;
        "foxy-hero": FoxyHero;
        "foxy-journal-renderer": FoxyJournalRenderer;
        "foxy-logo": FoxyLogo;
        "foxy-modal": FoxyModal;
        "foxy-nav": FoxyNav;
        "foxy-toast": FoxyToast;
        "foxy-toast-container": FoxyToastContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-about": LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
            "app-blog": LocalJSX.AppBlog & JSXBase.HTMLAttributes<HTMLAppBlogElement>;
            "app-case-studies": LocalJSX.AppCaseStudies & JSXBase.HTMLAttributes<HTMLAppCaseStudiesElement>;
            "app-contact": LocalJSX.AppContact & JSXBase.HTMLAttributes<HTMLAppContactElement>;
            "app-cs-craft-and-berry": LocalJSX.AppCsCraftAndBerry & JSXBase.HTMLAttributes<HTMLAppCsCraftAndBerryElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-services": LocalJSX.AppServices & JSXBase.HTMLAttributes<HTMLAppServicesElement>;
            "app-work-with-us": LocalJSX.AppWorkWithUs & JSXBase.HTMLAttributes<HTMLAppWorkWithUsElement>;
            "foxy-business-card": LocalJSX.FoxyBusinessCard & JSXBase.HTMLAttributes<HTMLFoxyBusinessCardElement>;
            "foxy-constellation": LocalJSX.FoxyConstellation & JSXBase.HTMLAttributes<HTMLFoxyConstellationElement>;
            "foxy-cta": LocalJSX.FoxyCta & JSXBase.HTMLAttributes<HTMLFoxyCtaElement>;
            "foxy-debate-takeover": LocalJSX.FoxyDebateTakeover & JSXBase.HTMLAttributes<HTMLFoxyDebateTakeoverElement>;
            "foxy-estimate": LocalJSX.FoxyEstimate & JSXBase.HTMLAttributes<HTMLFoxyEstimateElement>;
            "foxy-footer": LocalJSX.FoxyFooter & JSXBase.HTMLAttributes<HTMLFoxyFooterElement>;
            "foxy-hero": LocalJSX.FoxyHero & JSXBase.HTMLAttributes<HTMLFoxyHeroElement>;
            "foxy-journal-renderer": LocalJSX.FoxyJournalRenderer & JSXBase.HTMLAttributes<HTMLFoxyJournalRendererElement>;
            "foxy-logo": LocalJSX.FoxyLogo & JSXBase.HTMLAttributes<HTMLFoxyLogoElement>;
            "foxy-modal": LocalJSX.FoxyModal & JSXBase.HTMLAttributes<HTMLFoxyModalElement>;
            "foxy-nav": LocalJSX.FoxyNav & JSXBase.HTMLAttributes<HTMLFoxyNavElement>;
            "foxy-toast": LocalJSX.FoxyToast & JSXBase.HTMLAttributes<HTMLFoxyToastElement>;
            "foxy-toast-container": LocalJSX.FoxyToastContainer & JSXBase.HTMLAttributes<HTMLFoxyToastContainerElement>;
        }
    }
}
