/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface AppServices {
        "serviceType": 'ai' | 'shopify';
    }
    interface AppWorkWithUs {
    }
    interface FoxyConstellation {
    }
    interface FoxyEstimate {
    }
    interface FoxyFooter {
    }
    interface FoxyLogo {
        "size": 'small' | 'medium' | 'large';
    }
    interface FoxyNav {
        "active": boolean;
    }
}
export interface FoxyNavCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFoxyNavElement;
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppServicesElement extends Components.AppServices, HTMLStencilElement {
    }
    var HTMLAppServicesElement: {
        prototype: HTMLAppServicesElement;
        new (): HTMLAppServicesElement;
    };
    interface HTMLAppWorkWithUsElement extends Components.AppWorkWithUs, HTMLStencilElement {
    }
    var HTMLAppWorkWithUsElement: {
        prototype: HTMLAppWorkWithUsElement;
        new (): HTMLAppWorkWithUsElement;
    };
    interface HTMLFoxyConstellationElement extends Components.FoxyConstellation, HTMLStencilElement {
    }
    var HTMLFoxyConstellationElement: {
        prototype: HTMLFoxyConstellationElement;
        new (): HTMLFoxyConstellationElement;
    };
    interface HTMLFoxyEstimateElement extends Components.FoxyEstimate, HTMLStencilElement {
    }
    var HTMLFoxyEstimateElement: {
        prototype: HTMLFoxyEstimateElement;
        new (): HTMLFoxyEstimateElement;
    };
    interface HTMLFoxyFooterElement extends Components.FoxyFooter, HTMLStencilElement {
    }
    var HTMLFoxyFooterElement: {
        prototype: HTMLFoxyFooterElement;
        new (): HTMLFoxyFooterElement;
    };
    interface HTMLFoxyLogoElement extends Components.FoxyLogo, HTMLStencilElement {
    }
    var HTMLFoxyLogoElement: {
        prototype: HTMLFoxyLogoElement;
        new (): HTMLFoxyLogoElement;
    };
    interface HTMLFoxyNavElementEventMap {
        "menuClose": void;
    }
    interface HTMLFoxyNavElement extends Components.FoxyNav, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFoxyNavElementEventMap>(type: K, listener: (this: HTMLFoxyNavElement, ev: FoxyNavCustomEvent<HTMLFoxyNavElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFoxyNavElementEventMap>(type: K, listener: (this: HTMLFoxyNavElement, ev: FoxyNavCustomEvent<HTMLFoxyNavElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFoxyNavElement: {
        prototype: HTMLFoxyNavElement;
        new (): HTMLFoxyNavElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-services": HTMLAppServicesElement;
        "app-work-with-us": HTMLAppWorkWithUsElement;
        "foxy-constellation": HTMLFoxyConstellationElement;
        "foxy-estimate": HTMLFoxyEstimateElement;
        "foxy-footer": HTMLFoxyFooterElement;
        "foxy-logo": HTMLFoxyLogoElement;
        "foxy-nav": HTMLFoxyNavElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface AppServices {
        "serviceType"?: 'ai' | 'shopify';
    }
    interface AppWorkWithUs {
    }
    interface FoxyConstellation {
    }
    interface FoxyEstimate {
    }
    interface FoxyFooter {
    }
    interface FoxyLogo {
        "size"?: 'small' | 'medium' | 'large';
    }
    interface FoxyNav {
        "active"?: boolean;
        "onMenuClose"?: (event: FoxyNavCustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-services": AppServices;
        "app-work-with-us": AppWorkWithUs;
        "foxy-constellation": FoxyConstellation;
        "foxy-estimate": FoxyEstimate;
        "foxy-footer": FoxyFooter;
        "foxy-logo": FoxyLogo;
        "foxy-nav": FoxyNav;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-services": LocalJSX.AppServices & JSXBase.HTMLAttributes<HTMLAppServicesElement>;
            "app-work-with-us": LocalJSX.AppWorkWithUs & JSXBase.HTMLAttributes<HTMLAppWorkWithUsElement>;
            "foxy-constellation": LocalJSX.FoxyConstellation & JSXBase.HTMLAttributes<HTMLFoxyConstellationElement>;
            "foxy-estimate": LocalJSX.FoxyEstimate & JSXBase.HTMLAttributes<HTMLFoxyEstimateElement>;
            "foxy-footer": LocalJSX.FoxyFooter & JSXBase.HTMLAttributes<HTMLFoxyFooterElement>;
            "foxy-logo": LocalJSX.FoxyLogo & JSXBase.HTMLAttributes<HTMLFoxyLogoElement>;
            "foxy-nav": LocalJSX.FoxyNav & JSXBase.HTMLAttributes<HTMLFoxyNavElement>;
        }
    }
}
